In [7]:
## creating array
import array
arr= array.array('d', [2,4,6,8,10,12,14])
print("New created array.",end="")
for d in range (0,5):
  print (arr[d], end=" ")
  print("\r")


New created array.2.0 
4.0 
6.0 
8.0 
10.0 


In [16]:
#accessing the DataFrame  with boolean index
import pandas as pd
dict= {"name":["Puja","Pratik","William","Vijay"],
'age':["18","50","22","40"]}
info= pd.DataFrame(dict,index=[True,True,False,True])
print(info)

          name age
True      Puja  18
True    Pratik  50
False  William  22
True     Vijay  40


In [18]:
#another example on indexing
import pandas as pd
dict= {"name":["Puja","Pratik","William","Vijay"],
'age':["18","50","40","22"]}
info= pd.DataFrame(dict,index=[True,True,False,False])
print(info.loc[True])

        name age
True    Puja  18
True  Pratik  50


In [22]:
#reshaping arrays
import numpy as np
arr= np.arange(16)
print("The original array is: \n",arr)
arr= np.arange(16).reshape(2,8)
print("\nreshaped array: \n",arr)
arr = np.arange(16).reshape(8,2)
print("\nreshaped array: \n",arr)

The original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array: 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
